import { z } from 'zod';
import { BaseController, parseDocumentList, parseFirstDocument } from './base.js';
import {
  RoomReserveModelSchema,
  ROOM_RESERVE_COLLECTION_NAME,
  type RoomReserveModel,
  type ReserveQueryError,
} from '../models/roomReserve.js';
import type { Document } from '../models/base.js';
import type { RoomStayType, RoomReserveVisitType, RoomReserveState, OtaProvider } from '../types/enums.js';

/**
 * RoomReserve 생성 파라미터
 */
export interface RoomReserveCreateParams {
  /** 객실 ID */
  roomId?: string;
  /** 객실 유형 ID */
  roomTypeId?: string;
  /** 이용 유형 */
  stayType?: RoomStayType;
  /** 방문 유형 */
  visitType?: RoomReserveVisitType;
  /** 예약자명 */
  name?: string;
  /** 예약자 휴대폰 번호 */
  phone?: string;
  /** 체크인 예정 시간 */
  checkInSched?: number;
  /** 체크아웃 예정 시간 */
  checkOutSched?: number;
  /** 예약 요금 */
  fee?: number;
  /** 선불 금액 */
  prepaid?: number;
  /** 고객 메모 */
  memo?: string;
  /** 예약 주체 (OTA 에이전트) */
  agent?: OtaProvider;
  /** 예약 번호 */
  reserveNo?: string;
}

/**
 * RoomReserve 업데이트 파라미터
 */
export interface RoomReserveUpdateParams {
  /** 객실 ID */
  roomId?: string;
  /** 객실 유형 ID */
  roomTypeId?: string;
  /** 이용 유형 */
  stayType?: RoomStayType;
  /** 방문 유형 */
  visitType?: RoomReserveVisitType;
  /** 예약 상태 */
  state?: RoomReserveState;
  /** 예약자명 */
  name?: string;
  /** 예약자 휴대폰 번호 */
  phone?: string;
  /** 체크인 예정 시간 */
  checkInSched?: number;
  /** 체크아웃 예정 시간 */
  checkOutSched?: number;
  /** 예약 요금 */
  fee?: number;
  /** 선불 금액 */
  prepaid?: number;
  /** 고객 메모 */
  memo?: string;
}

/**
 * RoomReserve 검색 옵션
 */
export interface RoomReserveSearchOptions {
  /** 페이지당 개수 (필수, 1-100) */
  limit: number;
  /** 검색어 (예약자명, 휴대폰번호, 예약번호) */
  search?: string;
  /** 검색 시작 시간 (check_in_sched 기준) */
  startAt?: number;
  /** 검색 종료 시간 */
  endAt?: number;
  /** 객실 ID */
  roomId?: string;
  /** 객실 유형 ID */
  roomTypeId?: string;
  /** 자동 생성 여부 */
  autoGenerated?: boolean;
  /** 예약 상태 */
  state?: RoomReserveState;
  /** 방문 유형 */
  visitType?: RoomReserveVisitType;
  /** 이용 유형 */
  stayType?: RoomStayType;
}

/**
 * 예약 검색 가능 여부 응답 스키마
 */
const QueryAvailableResponseSchema = z.object({
  success: z.boolean().default(false),
  error: z.string().nullable().optional(),
  error_message: z.string().nullable().optional(),
  room_reserves: z.record(z.unknown()).optional(),
});

/**
 * 예약 검색 가능 여부 응답
 */
export interface QueryAvailableResponse {
  success: boolean;
  error: ReserveQueryError | null;
  errorMessage: string | null;
  roomReserves: Array<Document<RoomReserveModel>>;
}

/**
 * 파라미터를 API 요청 본문으로 변환
 */
function toApiBody(params: RoomReserveCreateParams | RoomReserveUpdateParams): Record<string, unknown> {
  const body: Record<string, unknown> = {};

  if (params.roomId !== undefined) body['room_id'] = params.roomId;
  if (params.roomTypeId !== undefined) body['room_type_id'] = params.roomTypeId;
  if (params.stayType !== undefined) body['stay_type'] = params.stayType;
  if (params.visitType !== undefined) body['visit_type'] = params.visitType;
  if ('state' in params && params.state !== undefined) body['state'] = params.state;
  if (params.name !== undefined) body['name'] = params.name;
  if (params.phone !== undefined) body['phone'] = params.phone;
  if (params.checkInSched !== undefined) body['check_in_sched'] = params.checkInSched;
  if (params.checkOutSched !== undefined) body['check_out_sched'] = params.checkOutSched;
  if (params.fee !== undefined) body['fee'] = params.fee;
  if (params.prepaid !== undefined) body['prepaid'] = params.prepaid;
  if (params.memo !== undefined) body['memo'] = params.memo;
  if ('agent' in params && params.agent !== undefined) body['agent'] = params.agent;
  if ('reserveNo' in params && params.reserveNo !== undefined) body['reserve_no'] = params.reserveNo;

  return body;
}

/**
 * RoomReserve Controller
 * 
 * 객실 예약 관련 CRUD 작업을 제공합니다.
 */
export class RoomReserveController extends BaseController {
  /**
   * 단일 예약 조회
   */
  async get(accomId: string, roomReserveId: string): Promise<Document<RoomReserveModel> | null> {
    const json = await this.client.get<Record<string, unknown>>(
      `/v1/room-reserve/${accomId}/${roomReserveId}`
    );
    return parseFirstDocument(json, ROOM_RESERVE_COLLECTION_NAME, RoomReserveModelSchema);
  }

  /**
   * 예약 목록 검색
   */
  async search(accomId: string, options: RoomReserveSearchOptions): Promise<{
    roomReserves: Array<Document<RoomReserveModel>>;
    nextStartAt: number | null;
  }> {
    const params = new URLSearchParams({
      limit: options.limit.toString(),
    });

    if (options.search !== undefined) params.set('search', options.search);
    if (options.startAt !== undefined) params.set('startAt', options.startAt.toString());
    if (options.endAt !== undefined) params.set('endAt', options.endAt.toString());
    if (options.roomId !== undefined) params.set('room_id', options.roomId);
    if (options.roomTypeId !== undefined) params.set('room_type_id', options.roomTypeId);
    if (options.autoGenerated !== undefined) params.set('auto_generated', options.autoGenerated.toString());
    if (options.state !== undefined) params.set('state', options.state);
    if (options.visitType !== undefined) params.set('visit_type', options.visitType);
    if (options.stayType !== undefined) params.set('stay_type', options.stayType);

    const json = await this.client.get<Record<string, unknown>>(
      `/v1/room-reserve/${accomId}?${params.toString()}`
    );

    const roomReserves = parseDocumentList(json, ROOM_RESERVE_COLLECTION_NAME, RoomReserveModelSchema);
    const nextStartAt = (json['next_start_at'] as number) ?? null;

    return { roomReserves, nextStartAt };
  }

  /**
   * 현재 예약된 (사용 가능한) 모든 예약 조회
   */
  async getAllByReserved(accomId: string): Promise<Array<Document<RoomReserveModel>>> {
    const json = await this.client.get<Record<string, unknown>>(
      `/v1/room-reserve/all-by-reserved/${accomId}`
    );
    return parseDocumentList(json, ROOM_RESERVE_COLLECTION_NAME, RoomReserveModelSchema);
  }

  /**
   * 예약 검색 (입실 가능 여부 확인)
   */
  async queryAvailable(
    accomId: string,
    searchText: string,
    options: {
      searchPhoneRightLength: number;
      searchReserveNoRightLength: number;
    }
  ): Promise<QueryAvailableResponse> {
    const params = new URLSearchParams({
      search_text: searchText,
      search_phone_right_length: options.searchPhoneRightLength.toString(),
      search_reserve_no_right_length: options.searchReserveNoRightLength.toString(),
    });

    const json = await this.client.get<Record<string, unknown>>(
      `/v1/room-reserve/query-available/${accomId}?${params.toString()}`
    );

    const result = QueryAvailableResponseSchema.parse(json);
    const roomReserves = parseDocumentList(json, ROOM_RESERVE_COLLECTION_NAME, RoomReserveModelSchema);

    return {
      success: result.success,
      error: (result.error as ReserveQueryError) ?? null,
      errorMessage: result.error_message ?? null,
      roomReserves,
    };
  }

  /**
   * 예약 생성
   */
  async create(
    accomId: string,
    params: RoomReserveCreateParams
  ): Promise<Document<RoomReserveModel> | null> {
    const body = toApiBody(params);
    const json = await this.client.post<Record<string, unknown>>(
      `/v1/room-reserve/${accomId}`,
      body
    );
    return parseFirstDocument(json, ROOM_RESERVE_COLLECTION_NAME, RoomReserveModelSchema);
  }

  /**
   * 예약 업데이트
   */
  async update(
    accomId: string,
    roomReserveId: string,
    params: RoomReserveUpdateParams
  ): Promise<Document<RoomReserveModel> | null> {
    const body = toApiBody(params);

    if (Object.keys(body).length === 0) {
      return null;
    }

    const json = await this.client.put<Record<string, unknown>>(
      `/v1/room-reserve/${accomId}/${roomReserveId}`,
      body
    );
    return parseFirstDocument(json, ROOM_RESERVE_COLLECTION_NAME, RoomReserveModelSchema);
  }

  /**
   * 예약 삭제
   */
  async delete(accomId: string, roomReserveId: string): Promise<Document<RoomReserveModel> | null> {
    const json = await this.client.delete<Record<string, unknown>>(
      `/v1/room-reserve/${accomId}/${roomReserveId}`
    );
    return parseFirstDocument(json, ROOM_RESERVE_COLLECTION_NAME, RoomReserveModelSchema);
  }
}
